name: Artifacts

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  create-v3:
    runs-on: ubuntu-latest

    steps:
      - name: create file
        run: |
          cat > file <<EOF
          hello
          world
          EOF
          date >> file

      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: test-v3
          path: file

      - name: Cleanup
        run: |
          rm -f file

      - name: retrieve artifact
        uses: actions/download-artifact@v3
        with:
          name: test-v3
      
      - name: Review
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          cat file
          rm -f file
          gh -R "$GITHUB_REPOSITORY" run download "$GITHUB_RUN_ID" -n test-v3 &&
            cat file ||
            echo "I guess gh can't download artifacts from the current run if they're uploaded with actions/upload-artifact@v3"

  retrieve-v3:
    runs-on: ubuntu-latest
    needs: create-v3

    steps:
      - name: retrieve artifact
        uses: actions/download-artifact@v3
        with:
          name: test-v3
      
      - name: Review
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          cat file
          rm -f file
          gh -R "$GITHUB_REPOSITORY" run download "$GITHUB_RUN_ID" -n test-v3
          find .
          cat file

  create-v4:
    runs-on: ubuntu-latest

    steps:
      - name: create file
        run: |
          cat > file <<EOF
          hello
          world
          EOF
          date >> file

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: test-v4
          path: file

      - name: Cleanup
        run: |
          rm -f file

      - name: retrieve artifact
        uses: actions/download-artifact@v4
        with:
          name: test-v4
      
      - name: Review
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          cat file
          rm -f file
          gh -R "$GITHUB_REPOSITORY" run download "$GITHUB_RUN_ID" -n test-v4 &&
            cat file ||
            echo "I guess gh can't download artifacts from the current run if they're uploaded with actions/upload-artifact@v3"

  retrieve-v4:
    runs-on: ubuntu-latest
    needs: create-v4

    steps:
      - name: retrieve artifact
        uses: actions/download-artifact@v4
        with:
          name: test-v4
      
      - name: Review
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          cat file
          rm -f file
          gh -R "$GITHUB_REPOSITORY" run download "$GITHUB_RUN_ID" -n test-v4
          find .
          cat file
