name: Artifacts

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  create:
    runs-on: ubuntu-latest

    steps:
      - name: create file
        run: |
          cat > file <<EOF
          hello
          world
          EOF
          date >> file

      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: test
          path: file

      - name: Cleanup
        run: |
          rm -f file

      - name: retrieve artifact
        uses: actions/download-artifact@v3
        with:
          name: test
      
      - name: Review
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          cat file
          rm -f file
          gh -R "$GITHUB_REPOSITORY" run download "$GITHUB_RUN_ID" -n test &&
            cat file ||
            echo "I guess gh can't download artifacts from the current run if they're uploaded with actions/upload-artifact@v3"

  retrieve:
    runs-on: ubuntu-latest
    needs: create

    steps:
      - name: retrieve artifact
        uses: actions/download-artifact@v3
        with:
          name: test
      
      - name: Review
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          cat file
          rm -f file
          gh -R "$GITHUB_REPOSITORY" run download "$GITHUB_RUN_ID" -n test
          find .
          cat file
